project_identifier: emberjs
api_key_env: CROWDIN_API_KEY
base_path: './source/localizable'

files:
  - source: '/**/*.md'
    translation: '/**/%file_name%.%locale%.%file_extension%'
    ignore:
      - '/**/**.*.md'
